"""Add security features

Revision ID: 19ff97e0dcca
Revises: 
Create Date: 2024-12-31 19:11:13.788026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ff97e0dcca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remember_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('backup_codes', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('password_changed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('previous_passwords', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lock_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('session_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_action', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('action_count', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_user_remember_token', ['remember_token'])
        batch_op.create_unique_constraint('uq_user_reset_token', ['reset_token'])
        batch_op.create_unique_constraint('uq_user_verification_token', ['verification_token'])
        batch_op.create_unique_constraint('uq_user_session_token', ['session_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_session_token', type_='unique')
        batch_op.drop_constraint('uq_user_verification_token', type_='unique')
        batch_op.drop_constraint('uq_user_reset_token', type_='unique')
        batch_op.drop_constraint('uq_user_remember_token', type_='unique')
        batch_op.drop_column('action_count')
        batch_op.drop_column('last_action')
        batch_op.drop_column('session_expires_at')
        batch_op.drop_column('session_token')
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('lock_expires_at')
        batch_op.drop_column('account_locked')
        batch_op.drop_column('previous_passwords')
        batch_op.drop_column('password_expires_at')
        batch_op.drop_column('password_changed_at')
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('last_login')
        batch_op.drop_column('remember_token')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
